name: Xendit Coding Excercise CI

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: '9'
          cache: 'npm'
        run: npm install
        run: npm test