name: Xendit Coding Excercise CI

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '9'
          cache: 'npm'
      - name: Test
        run: npm install
        run: npm test